services:

  web:
    build: .
    container_name: paraiso-tropical
    ports:
      - "8080:80"

  spark:
    image: spark
    container_name: spark
    volumes:
      - ./data:/data
      - ./spark:/app
    command: tail -f /dev/null